### ISSUE TITLE
PHP form to JavaScript (2 php files into 1 javascript/html file)

### ISSUE THREAD

**Issue by mikestratton** [mikestratton/simplemap#2]
There are two files, 
v0.06.php is a form that inputs latitude and longitude into a map.
v0.06.2.php takes data from form and inputs into map.

A full server trip and php is not needed. Turn these two files into one html/javascript file.

For this to work properly, you will need a google developers account and a google maps API Key

[upwork_lat_lon.zip](https://github.com/mikestratton/simplemap/files/531540/upwork_lat_lon.zip)

**Comment by bryanjhv** [comment]
Should this be made in an instant way (I mean, XMLHttpRequest), or by sending the data to the same page and refreshing that page with the new values (common POST request)?

**Comment by mikestratton** [comment]
No, it should be done in same page. Thanks.

**Comment by bryanjhv** [comment]
Working on that right now! :smile:

**Comment by mikestratton** [comment]
Thanks! :)

**Comment by mikestratton** [comment]
@bryanjhv Are you on Upwork.com?

**Comment by bryanjhv** [comment]
No, I'm not working right now, still in college. :smile: But I'm on [wizpert.com](https://wizpert.com/bryanjhv).

**Comment by mikestratton** [comment]
You will be working soon enough!

Get Outlook for iOS

On Sun, Oct 16, 2016 at 8:38 PM -0400, "Bryan Horna" notifications@github.com wrote:

No, I'm not working right now, still in college. 😄
