### ISSUE TITLE
Subtask #1 from: Saving Map to URL

### ISSUE THREAD

**Issue by mikestratton** [mikestratton/simplemap#5]
Please review:
https://github.com/mikestratton/simplemap/issues/4
before working on this issue.
- [ ] An index file is updated adding a new file name.

**Comment by bryanjhv** [comment]
Can you provide more details for working on this? PHP needs to be used, ...?

**Comment by mikestratton** [comment]
Yes PHP is ok.

**Comment by mikestratton** [comment]
Preferably PHP

**Comment by mikestratton** [comment]
This is the original file: 
https://github.com/mikestratton/simplemap/blob/master/create_json_file.html

**Comment by mikestratton** [comment]
Don't forget to do pull request to your repository as I have made updates.
git status
git pull
